export const REQUEST_WEATHER = 'REQUEST_WEATHER';
export type REQUEST_WEATHER = typeof REQUEST_WEATHER;

export const REQUEST_NEWCITY_WEATHER = 'REQUEST_NEWCITY_WEATHER';
export type REQUEST_NEWCITY_WEATHER = typeof REQUEST_NEWCITY_WEATHER;

export const RECEIVE_WEATHER = 'RECEIVE_WEATHER';
export type RECEIVE_WEATHER = typeof RECEIVE_WEATHER;

export const RECEIVE_NEWCITY_WEATHER = 'RECEIVE_NEWCITY_WEATHER';
export type RECEIVE_NEWCITY_WEATHER = typeof RECEIVE_NEWCITY_WEATHER;

export const REMOVE_CURRENT_CITY = 'REMOVE_CURRENT_CITY';
export type REMOVE_CURRENT_CITY = typeof REMOVE_CURRENT_CITY;

export const SET_CURRENT_CITY = 'SET_CURRENT_CITY';
export type SET_CURRENT_CITY = typeof SET_CURRENT_CITY;

export const SET_FAVORITE_CITIES = 'SET_FAVORITE_CITIES';
export type SET_FAVORITE_CITIES = typeof SET_FAVORITE_CITIES;
