export const REQUEST_WEATHER = 'REQUEST_WEATHER';
export type REQUEST_WEATHER = typeof REQUEST_WEATHER;

export const RECEIVE_WEATHER = 'RECEIVE_WEATHER';
export type RECEIVE_WEATHER = typeof RECEIVE_WEATHER;

export const REMOVE_CURRENT_CITY = 'REMOVE_CURRENT_CITY';
export type REMOVE_CURRENT_CITY = typeof REMOVE_CURRENT_CITY;

export const SET_CURRENT_CITY = 'SET_CURRENT_CITY';
export type SET_CURRENT_CITY = typeof SET_CURRENT_CITY;

export const REQUEST_WEATHER_FAVORITS = 'REQUEST_WEATHER_FAVORITS';
export type REQUEST_WEATHER_FAVORITS = typeof REQUEST_WEATHER_FAVORITS;

export const RECEIVE_WEATHER_FAVORITS = 'RECEIVE_WEATHER_FAVORITS';
export type RECEIVE_WEATHER_FAVORITS = typeof RECEIVE_WEATHER_FAVORITS;
